---
title: "Modeling Food and Housing Insecurity at UTEP - Phase 1"
subtitle: "Data Preprocessing and Exploration"
author: 
 - "George E. Quaye"
 - "John Koomson"
 - "Willliam O. Agyapong"
  
affiliation: "Department of Mathematical Sciences, University of Texas at El Paso"
date: \center University of Texas, El Paso (UTEP)\center
       \center Department of Mathematical Sciences \center
output:
  html_document:
    fig_caption: yes
    keep_tex: no
    number_sections: yes
    toc: yes
    toc_depth: 4
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    number_sections: yes
    toc: yes
    toc_depth: 4
header-includes:
  - \usepackage{float}
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{bm}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{amsfonts}
  - \usepackage{amsthm}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \rhead{George Quaye, Johnson Koomson, William Agyapong}
  - \lhead{Analysis Plan - DS 6335}
  - \cfoot{\thepage}
  - \usepackage{algorithm}
  - \usepackage[noend]{algpseudocode}
geometry: margin = 0.8in
fontsize: 10pt
bibliography: references.bib
link-citations: yes
linkcolor: blue
csl: apa-6th-edition-no-ampersand.csl
nocite: |
---
\end{center}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

# Load required packages
library(dplyr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
library(ggcorrplot) # for correlation plot
library(ggthemes)
library(patchwork)
library(knitr)
# library(kableExtra)
library(scales) # for the percent function
```


```{r data-reading}
file_path <- dirname(rstudioapi::getSourceEditorContext()$path)
FIHI <- read.csv(paste0(file_path, '/datcsv.csv'))


#=========================================================
# Helper functions
#========================================================

na_to_zero <- function(x) 
{
  return(ifelse(is.na(x), 0, x ))
}

# This function helps restore back any prior missingness. Care must be taken in 
# order not to apply it to a variable where 0 has a different meaning.
zero_to_na <- function(x) 
{
  return(ifelse(x == 0, NA, x ))
}

```



```{r data-preprocessing}

FIHI_new <- FIHI %>% 
  # change column names to lowercase
  rename_with(tolower) %>%
  # Removing unwanted variables
  select(-externalid, -satellite, -email, -datetime, -carddata,
                        -starts_with(c("q5", "q8","q16", "q18", "q21", "q29", "q24", "q36", "q37", "q38", "q39"))
         ) %>%
  # Strip off trailing strings to get clean variable names
  rename_with(~gsub('\\..*', '', .x))  


##------- Consolidating common variables split across levels -----
 # We create dummy columns for the number of non-na values within each range for the targeted variable
FIHI_new_ <- FIHI_new %>% 
  mutate(q6Count = rowSums(!is.na(select(., starts_with("q6")))),
         q7Count = rowSums(!is.na(select(., starts_with("q7")))),
         q11Count = rowSums(!is.na(select(., starts_with("q11")))),
         q25Count = rowSums(!is.na(select(., starts_with("q25"))))) %>%
  # change the 0 level for q25_7 to avoid issues with approach for working on these multiple-response variables
  mutate(q25_7 = ifelse(q25_7 == 0, 7, q25_7))

## View these variables to make sure the count was done right
# FIHI_new_%>%select(respondentid,starts_with("q6")) %>%kable()
# FIHI_new_%>%select(respondentid,starts_with("q7")) %>%kable()
# FIHI_new_%>%select(respondentid,starts_with("q11")) %>%kable()
# FIHI_new_%>%select(respondentid,starts_with("q25")) %>%kable()


##-------------- Separating multiple responses ---------------------------------
# Ethnicity: 
#    - level 8 is for mixed race
#    - set Hispanic and White/Caucassian to Hispanic [q6_1!=0 & q6_6!=0]
#    - set Hispanic and Black to Black [q6_1!=0 & q6_4!=0]
#
# Gender:
#    - level 7: Mixed gender
#
# Federal Aid (q25): 
#    - Not applicable -> 7
#    - Multiple sources -> 8
#    - work study is almost lost when multiple responses are sorted out, 
#    so we decided to do: work study + other sources => work study
#    - 
#
FIHI_sub <- FIHI_new_ %>% 
  mutate(across(starts_with(c("q6", "q7", "q11", "q25")), na_to_zero)) %>%
  mutate(q6 = ifelse(q6Count>1, ifelse(q6_1!=0 & q6_6!=0, 1,
                                       ifelse(q6_1!=0 & q6_4!=0, 4, 8)
                                       ),
                     rowSums(across(starts_with("q6_")))), 
  
         q7 = ifelse(q7Count>1, 7, rowSums(across(starts_with("q7_")))),
         
         q11 = ifelse(q11Count>1,10, rowSums(across(starts_with("q11_")))),
         
         q25 = ifelse(q25Count>1, ifelse(q25_2!=0, 2, 8), 
                      rowSums(across(starts_with("q25_")))),
         
         .after = starts_with("q4"),
         .keep = "unused") %>%
  relocate(q11, .after = starts_with("q10")) %>% # just to keep the order of the variables
  relocate(q25, .after = starts_with("q23")) %>%
  mutate(across(starts_with(c("q6", "q7", "q11", "q25")), zero_to_na))

# test_df <- FIHI_sub %>% mutate(across(!respondentid, as.factor)) # convert all variables except the respondent id to a factor


##---------- Collapsing levels within some of the variables ---------
#
# Ethnicity(q6): maintain Hispanic (1), Black/African American(4), White(6), Asian(3)
# and collapse American Indian(2), Native Hawaiian(5), mixed race(8) and other(7) into other (8).
# We decided not to keep a mixed race level because the total came to 88 after we 
# assigned (Hispanic, white) to Hispanic, and (Hispanic, Black) to Black.
#
# Gender(q7) now will have only 3 levels (female -> 1, male -> 2, non-binary/non-conforming -> 3).
#
# Income(q9): keep first 5 levels and 100000 or more (11)->8, collapse (6,7)->6, (8,9,10)->7
# 
# Academic level (q10): keep first 5, and collapse last 2 -> 6 
#
# College (q11): maintain first 6, put rest into other (level 7)
#
# Commute (q12): keep car(1), Bus/public (4) and other(8), collapse car & carpool (2,3) -> 9,
# collapse bike, trolley, walk (5,6,7) -> 10. Keep Not applicable (0)
#
# Federal Aid(q25): Emergency loan reduced from 316 to 50, so we added those to loans(3)
#
# Q26: Never -> 1, sometimes true -> 2, often true -> 3
##

FIHI_sub2 <- FIHI_sub %>%
  mutate(q6 = ifelse(q6%in%c(2,5,7,8), 8, q6),
         q7 = ifelse(q7 >=4, 3, q7),
         q9 = ifelse(q9%in%c(6,7), 12, ifelse(q9%in%c(8,9,10), 13, q9)),
         q10 = ifelse(q10>5, 6, q10),
         # q11 = ifelse(q11>6, 7, q11),
         q12 = ifelse(q12%in%2:3, 9, ifelse(q12%in%5:7, 10, ifelse(q12==0, 11, q12))),
         q25 = ifelse(q25==4, 3, q25)
         )

##------------------ Assign labels to the various levels -----------------------
FIHI_sub3 <- FIHI_sub2 %>%
  mutate(
    q1 = factor(q1, levels = 1:2, 
                      labels = c("Full Time", "Part Time")),
    q2 = factor(q2, levels = 1:3, 
                      labels = c("Full Time", "Part Time", "No")),
    q3 = factor(q3, levels = 1:2, 
                      labels = c("On-Campus", "Off-Campus")),
    q4 = factor(q4, levels = 1:2, 
                      labels = c("19 hours or less", "More than 19 hours")),
    q6 = factor(q6, levels = c(1,3,4,6,8), 
                      labels = c("Hispanic", "Asian", "Black/African American", "White/Caucasian",
                                 "Other")),
    q7 = factor(q7, levels = 1:3, 
                      labels = c("Female", "Male", "Non-binary/Non-conforming")),
    q9 = factor(q9, levels = c(1:5,12,13,11), 
                      labels = c("< 10,000", "10,000-19,999", "20,000-29,999", "30,000-39,000",
                                 "40,000-49,999", "50,000-69,999", "70,000-99,999", ">=100,000")),
    q10 = factor(q10, levels = 1:6, 
                      labels = c("Freshman", "Sophomore", "Junior", "Senior",
                                 "Masters", "Doctoral/Professional")),
    q11 = factor(q11, levels = 1:10, 
                      labels = c("Business", "Education", "Engineering", "Health Sciences",
                                 "Liberal Arts", "Science", "Nursing", "Pharmacy",
                                 "Other", "More than one")),
    q12 = factor(q12, levels = c(1,9,4,10,8,11), 
                      labels = c("Car (alone)", "Car (someone drives) & Carpool",
                                 "Bus/Public transport", "Bike, Trolley, or Walk",
                                 "Other", "Not applicable")),
    q13 = factor(q13, levels = 1:4, 
                      labels = c("Not reliable at all", "Somewhat reliable",
                                 "Fairly reliable", "Very reliable")),
    q14 = factor(q14, levels = 1:2, 
                      labels = c("Yes", "No")),
    q15 = factor(q15, levels = 1:2, 
                      labels = c("Yes", "No")),
    q17 = factor(q17, levels = 1:2, 
                      labels = c("Yes", "No")),
    q19 = factor(q19, levels = 1:4, 
                      labels = c("On-Campus", "Off-Campus with family", 
                                 "Off-Campus not with family", "Other")),
    q20 = factor(q20, levels = 1:2, 
                      labels = c("Yes", "No")),
    q22 = factor(q22, levels = 1:3, 
                      labels = c("Rarely", "Sometimes", "Often")),
    q23 = factor(q23, levels = 1:2, 
                      labels = c("Yes", "No")),
    q25 = factor(q25, levels = c(1:3,5,8,7,6 ), 
                      labels = c("Grants", "Work Study", "Loans", "Scholarship", 
                                 "Multiple Aids", "Other", "None")),
    q26 = factor(q26, levels = 1:3, 
                      labels = c("Never true", "Sometimes true", "Often true")),
    q27 = factor(q27, levels = 1:3, 
                      labels = c("Never true", "Sometimes true", "Often true")),
    q28 = factor(q28, levels = 1:2, 
                      labels = c("Yes", "No")),
    q30 = factor(q30, levels = 1:2, 
                      labels = c("Yes", "No")),
    q31 = factor(q31, levels = 1:2, 
                      labels = c("Yes", "No")),
    q32 = factor(q32, levels = 1:3, 
                      labels = c("Decreased", "About the same", "Increased")),
    q33 = factor(q33, levels = 1:3, 
                      labels = c("Decreased", "About the same", "Increased")),
    q34 = factor(q34, levels = 1:3, 
                      labels = c("Decreased", "About the same", "Increased")),
    q35 = factor(q35, levels = 1:3, 
                      labels = c("Decreased", "About the same", "Increased")),
    )

##------------- Rename the remaining variables ---------------------
var_names <- c("respondent_id", "enrollment", "employment", "employment_type", "weekly_work_hrs", "ethnicity", "gender", "total_income", "academic_level", "college/school", "mode_transport", "transport_reliability", "living_alone", "dependents", "household_head", "residence", "permanent_address", "spent_night_elsewhere", "know_homelessness_studt", "federal_aid", "FI_q26", "FI_q27", "FI_q28", "FI_q30", "FI_q31", "expenditures_changed", "income_changed", "fed_aid_changed", "debt_changed")

names(FIHI_sub2) <- var_names
names(FIHI_sub3) <- var_names



# Save preprocessed file 
# write.csv(FIHI_sub3, paste0(file_path, '/datcsv_clean.csv'))

save(FIHI_sub2, FIHI_sub3, file=paste0(file_path, '/FIHI_clean.RData'))


```

# Exploratory Data Analysis

## Visualizing Missing Data 
```{r}
# install.packages("naniar")
# install.packages("UpSetR")
library(naniar)
library(UpSetR)

# explore the patterns
gg_miss_upset(FIHI_sub3)

# explore missingness in variables with gg_miss_var
miss_var_summary(FIHI_sub3) %>% kable()

gg_miss_var(FIHI_sub3) + ylab("Number of missing values")

gg_miss_var(FIHI_sub3, show_pct = T) 
```


## Distribution of Housing Insecurity Responses
```{r}

# Permanent Address
plotdf <- FIHI_sub3 %>%
  group_by(permanent_address) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p1 <- ggplot(plotdf, aes(permanent_address,n, fill=as.factor(permanent_address))) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Had permanent address in the past 12 months?", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")


# Spending night elsewhere
plotdf <- FIHI_sub3 %>%
  filter(permanent_address=='No') %>%
  group_by(spent_night_elsewhere) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p2 <- ggplot(plotdf, aes(spent_night_elsewhere,n, fill=as.factor(spent_night_elsewhere))) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="How fequently did you spend the night elsewhere?", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")

# Display plots side by side
p1 + p2
```

## Distribution of Food Insecurity Responses
```{r}

# Q26: Food bought didn't last
plotdf <- FIHI_sub3 %>%
  group_by(FI_q26) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p1 <- ggplot(plotdf, aes(FI_q26,n, fill=FI_q26)) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Food bought didn't last", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")


# Q27: Balanced diet
plotdf <- FIHI_sub3 %>%
  group_by(FI_q27) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p2 <- ggplot(plotdf, aes(FI_q27,n, fill=FI_q27)) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Couldn't afford balanced meals", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")


# Q27: Balanced diet
plotdf <- FIHI_sub3 %>%
  group_by(FI_q28) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p3 <- ggplot(plotdf, aes(FI_q28,n, fill=FI_q28)) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Ever cut the size of meals?", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")

# Q27: Balanced diet
plotdf <- FIHI_sub3 %>%
  group_by(FI_q30) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p4 <- ggplot(plotdf, aes(FI_q30,n, fill=FI_q30)) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Ever ate less than you should?", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")


# Q27: Balanced diet
plotdf <- FIHI_sub3 %>%
  group_by(FI_q31) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p5 <- ggplot(plotdf, aes(FI_q31,n, fill=FI_q31)) + 
  geom_bar(stat = "identity",position = "dodge")  +
  geom_text(aes(label = n), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Ever hungry but didn't eat?", y="Number of Respondents", title="") +
  theme_classic() +
  theme(legend.position = "none")

# Display plots side by side
(p1 + p2)

(p3 + p4)

p5
```


##  The effect of potential categorical predictors on  responses.

```{r warning=F, message=F, echo=F, eval=F}
plotdf <- heart_dat %>%
  group_by(sex, death_event) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p1 <- ggplot(plotdf, aes(sex, pct, fill=death_event)) + 
  geom_bar(stat = "identity",position = "fill") +
  scale_y_continuous(breaks = seq(0,1,0.2), label=percent) +
  geom_text(aes(label = lbl), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Sex",y="Percent of patients", fill="Death Event") +
  theme_classic() +
  theme(legend.position = "none")

plotdf <- heart_dat %>%
  group_by(anaemia, death_event) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p2 <- ggplot(plotdf, aes(anaemia, pct, fill=death_event)) + 
  geom_bar(stat = "identity",position = "fill") +
  scale_y_continuous(breaks = seq(0,1,0.2), label=percent) +
  geom_text(aes(label = lbl), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Anaemia status",y="", fill="Death Event") +
  theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

plotdf <- heart_dat %>%
  group_by(diabetes, death_event) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p3 <- ggplot(plotdf, aes(diabetes, pct, fill=death_event)) + 
  geom_bar(stat = "identity",position = "fill") +
  scale_y_continuous(breaks = seq(0,1,0.2), label=percent) +
  geom_text(aes(label = lbl), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Diabetes status",y="Percent of patients", fill="Death Event") +
  theme_classic() +
  theme(legend.position = "none")

plotdf <- heart_dat %>%
  group_by(HBP, death_event) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p4 <- ggplot(plotdf, aes(HBP, pct, fill=death_event)) + 
  geom_bar(stat = "identity",position = "fill") +
  scale_y_continuous(breaks = seq(0,1,0.2), label=percent) +
  geom_text(aes(label = lbl), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="HBP status",y="", fill="Death Event") +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

plotdf <- heart_dat %>%
  group_by(smoking, death_event) %>%
  summarise(n=n()) %>% 
  mutate(pct = n/sum(n),
         lbl = percent(pct))

p5 <- ggplot(plotdf, aes(smoking, pct, fill=death_event)) + 
  geom_bar(stat = "identity",position = "fill") +
  scale_y_continuous(breaks = seq(0,1,0.2), label=percent) +
  geom_text(aes(label = lbl), size=3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette="Set2") + 
  labs(x="Smoking status",y="", fill="Death Event") +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
        )

# display plots in a grid layout
(p1 + p2) / (p3 + p4 + p5)
```


```{r}

```


# References{-}

<div id="refs"></div>


